name: build-application
run-name: application-builder-${{ github.actor }}
on: [push]

env:
    DOTNET_SDK_VERSION: 8.x.x

jobs:
    build:
        environment: Production
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Setting up .NET ${{ env.DOTNET_SDK_VERSION }}
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
            - name: Setting up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Fetching .env
              working-directory: ./App
              run: |
                echo "NAMA=${{ secrets.APP_NAMA }}" > .env
                echo "NRP=${{ secrets.APP_NRP }}" > .env
            - name: Installing dependencies
              working-directory: ./App
              run: dotnet restore
            - name: Compiling application
              working-directory: ./App
              run: ./compile.sh
            - name: Checking compiled application
              working-directory: ./Dockerfile/publish
              run: ls -al
            - name: Building docker image
              working-directory: ./App
              run: ./docker.sh